version: "3.7"
services:
  db:
    image: postgres:15
    container_name: db_app
    env_file:
      - .env
  
  app:
    build:
      context: . 
    
    env_file:
      - .env
    container_name: hakaton_app
    command: ["/hakaton_app/docker/app.sh"]
    ports:
      - 9999:8000
    depends_on:
      - db